### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by utkarsh006**
- View Changes [HERE](https://github.com/utkarsh006/status/blob/Readme_update/README.md)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@dduportal Kindly Review.

**Review by dduportal — CHANGES_REQUESTED** [review]
Hi @utkarsh006 thanks for opening this pull request.

May I ask you the reason of this change? Did you have any issue with the curent README or see improvement?

Also, we want to stick using asciidoctor in this repository. The main reason is because the status.jenkins.io source is written in Asciidoctor (files `*.adoc`) so we want to keep this language for the README as well.

**Comment by utkarsh006** [comment]
@dduportal I have just concised the README file and presented the text written in a well-structured form. I think we can migrate the README file to .md extension since it will be easy to handle it and also it is a widely accepted markdown format.

**Comment by dduportal** [comment]
> @dduportal I have just concised the README file and presented the text written in a well-structured form. I think we can migrate the README file to .md extension since it will be easy to handle it and also it is a widely accepted markdown format.

As I said earlier, we stick to asciidoctor. We won't change the file format to markdown while the rest of the repository is using asciidoctor.

Feel free to apply the proposed rendering changes to the current `README.adoc` as it looks like it's improving the readability though!

**Comment by MarkEWaite** [comment]
Closing after two weeks with no response.

**Pull request closed without merging**
